### ISSUE TITLE
Error when getting project from Git (Database Error)

### ISSUE THREAD

**Issue by kuroiNOryuu** [StefanEggenschwiler/644-1_DemoApplication#1]
![644-1_demoapplication_import_error](https://user-images.githubusercontent.com/8030802/32104769-1f4ad9e2-bb26-11e7-9ddb-40c73af62c7b.png)

**Comment by kuroiNOryuu** [comment]
![644-1_demoapplication_import_error2](https://user-images.githubusercontent.com/8030802/32106778-f1dcff4c-bb2c-11e7-838d-daa2c2daf5b8.png)

**Comment by StefanEggenschwiler** [comment]
Hello,
I played around a little bit with the .gitignore entries and ignored another Android Studio specific file.
Could you clone the repository again and try to import it to Android Studio? During the initial gradle build process you might see an error message, just ignore it. (in 1 of 3 test tries an error was displayed)

After the process has finished, you might see an error in the run configurations:
![run_configuration](https://user-images.githubusercontent.com/1685438/32132434-bf606f08-bbc3-11e7-9731-87b1d8b8c0ae.PNG)

If you get this error, just rerun the gradle build process:
![gradle](https://user-images.githubusercontent.com/1685438/32132446-e77acca4-bbc3-11e7-8c20-29389a2e953f.PNG)

Afterwards the project should work as expected. :-)

**Comment by kuroiNOryuu** [comment]
I imported the project again, closed Android Studio, rerun the gradle build and it's all okay now, it's working. Thanks a lot for your help!
